// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk5L8dgsaHxtfkOjNf5a34moN-FpvUXbM',
    appId: '1:18427192478:web:aef8394d7e6f465c27c78f',
    messagingSenderId: '18427192478',
    projectId: 'model-home-app',
    authDomain: 'model-home-app.firebaseapp.com',
    storageBucket: 'model-home-app.firebasestorage.app',
    measurementId: 'G-F1TKPD803N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZN1XsV9MLc0ku9PkzHTfv6ptLGnABJpA',
    appId: '1:18427192478:android:655803e65040c79927c78f',
    messagingSenderId: '18427192478',
    projectId: 'model-home-app',
    storageBucket: 'model-home-app.firebasestorage.app',
  );
}
